config/routes.rb
Rails.application.routes.draw do
  root 'flights#index'

  resources :flights, only: :index
  resources :bookings, only: [:show, :new, :create]
end

app/models/airport.rb
class Airport < ApplicationRecord
  has_many :arrivals,
           class_name: 'Flight',
           foreign_key: :destination_id,
           dependent: :destroy
  has_many :departures,
           class_name: 'Flight',
           foreign_key: :origin_id,
           dependent: :destroy
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  has_many :passengers, inverse_of: :booking
  belongs_to :flight
  accepts_nested_attributes_for :passengers

  validates :flight_id, presence: true
end

app/models/flight.rb
class Flight < ApplicationRecord
  belongs_to :origin, class_name: 'Airport'
  belongs_to :destination, class_name: 'Airport'
  has_many :bookings
  has_many :passengers, through: :bookings

  default_scope { order(price: :asc) }

  validates_uniqueness_of :id

  def self.search(origin, destination, date)
    where("origin_id = ? AND
           destination_id = ? AND
           departure_date BETWEEN ? AND ?",
           origin, destination,
           date.at_midnight, date.at_end_of_day)
  end
end

app/models/passenger.rb
class Passenger < ApplicationRecord
  belongs_to :booking

  validates :first_name, :last_name, :email, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController

  def index
  end

  def show
    @booking = Booking.find(params[:id])
    @flight = Flight.find_by_id(@booking.flight_id).decorate
    @passengers = @booking.passengers.decorate
  end

  def new
    @flight = Flight.find_by_id(params[:flight_id]).decorate
    @booking = @flight.bookings.build
    @seats = params[:seats].to_i
    @seats.times { @booking.passengers.build }
  end

  def create
    @flight = Flight.find_by_id(params[:booking][:flight_id]).decorate
    @booking = @flight.bookings.build(booking_params)
    if @booking.save
      @booking.passengers.each do |passenger|
        PassengerMailer.booking_confirmation(passenger, @booking).deliver_now!
      end
      flash[:success] = 'You successfuly bought tickets!'
      redirect_to @booking
    else
      Rails.logger.info(@booking.errors.inspect)
      flash[:danger] = 'Booking was unsuccessful'
      render 'new'
    end
  end

  private

  def booking_params
    params.require(:booking).permit(:flight_id,
                                    passengers_attributes: [:first_name,
                                                            :last_name,
                                                            :email,
                                                            :booking_id])
  end
end

app/controllers/flights_controller.rb
class FlightsController < ApplicationController

  def index
    @airports = Airport.all
    @flight_dates = Flight.pluck(:departure_date).map(&:to_date).uniq.sort
    if params[:flight]
      @flights = Flight.includes(:origin, :destination)
                       .search(params[:flight][:origin],
                               params[:flight][:destination],
                               params[:flight][:departure_date].to_date).decorate
    end
    respond_to do |format|
      format.js {  render layout: false }
      format.html
    end
  end
end

app/controllers/passengers_controller.rb
class PassengersController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/helpers/flights_helper.rb
module FlightsHelper
end

app/helpers/passengers_helper.rb
module PassengersHelper
end

app/views/bookings/new.html.slim
.container
  .row
    .col.s12
      h3.center-align Booking info
      ul.collection
        = render 'flights/flight', flight: @flight

      h4.center-align Passengers info
      = form_for @booking do |f|
        = f.hidden_field :flight_id
        ul.collection
          = f.fields_for :passengers do |p|
            = render 'passengers/form', p: p
        h5.center-align= "Total: #{@flight.price * @seats} EUR"
        .row
          .col.s2.offset-s3.offset-m4.offset-l5
            = f.submit 'Buy tickets', class: 'waves-effect waves-light btn-large'

app/views/bookings/show.slim
.container
  .row
    .col.s12
      h3.center-align Your booking
      ul.collection
        = render 'flights/flight', flight: @flight
      .col.s12
        h5.right= "Total: #{@flight.price * @passengers.count} EUR"
      h4.center-align Passengers
      ul.collection
        = render @passengers

app/views/flights/_flight.slim
li.collection-item.avatar[style='cursor: pointer;']
  = radio_button_tag :flight_id, flight.id, false
  i.material-icons.circle.cyan.darken-3 flight_takeoff
  div.valign-wrapper
    h6.title = "#{flight.origin.city} (#{flight.origin.code})"
    i.material-icons trending_flat
    h6.title = "#{flight.destination.city} (#{flight.destination.code})"
  p
    | Date:
    = flight.view_date
  p
    | Time:
    = flight.view_time
  p
    | Duration:
    = flight.view_duration
  h5.right-align= flight.view_price

app/views/flights/_form.slim
= form_tag flights_path, method: :get, remote: true
  .col.s12.l6
    = label_tag 'Origin'
    = collection_select :flight, :origin, @airports, :id, :city,
                        selected: params.dig(:flight, :origin)
  .col.s12.l6
    = label_tag 'Destination'
    = collection_select :flight, :destination, @airports, :id, :city,
                        selected: params.dig(:flight, :destination)
  .col.s12.l6
    = label_tag 'Date'
    = select :flight, :departure_date, @flight_dates,
             selected: params.dig(:flight, :departure_date)
  .col.s12.l6
    = label_tag 'Passengers'
    = select_tag :seats, options_for_select(1..4, params[:seats])
  .col.s4.offset-s3.offset-m4.offset-l5
    = submit_tag 'Search', class: 'waves-effect waves-light btn-large'

app/views/flights/_select_flight.slim
- if @flights.any?
  h3.center-align Select flight
  = form_tag new_booking_path, method: :get,
                               class: 'row',
                               id: 'select_flight_form' do
    = hidden_field_tag :seats, params[:seats]
    ul.collection.z-depth-2
      = render @flights
    .col.s4.offset-s3.offset-m4.offset-l5
      = submit_tag 'Book flight',
                   class: 'waves-effect waves-light btn-large',
                   id: 'select_flight_button'
- else
  h5.center-align No flights found for that criteria. Search again?

app/views/flights/index.js.erb
$('.select_flight').html('<%= j render("flights/select_flight") %>').fadeIn('slow');
$('.collection-item').first().addClass('active').find("input[type='radio']").attr('checked', 'checked');
$('#spinner').css('visibility', 'hidden');
$('html, body').animate({ scrollTop: $('.select_flight').offset().top }, 'slow');

app/views/flights/index.slim
.container
  .row
    .col.s12
      .card-panel
        h3.center-align Search for flights
        .row
          .col.s12
            = render 'form'
      .select_flight.col.s12[style='display: none']

app/views/layouts/_navbar.slim
nav
  = render 'shared/spinner'
  .nav-wrapper
    = link_to 'FlightBooker', root_path, class: 'brand-logo'
    a.button-collapse data-activates="mobile-demo" href="#"
      i.material-icons menu
    ul.right.hide-on-med-and-down
      li
        = link_to 'Search flights', root_path

    ul#mobile-demo.side-nav
      li
        = link_to 'Search flights', root_path

app/views/layouts/application.slim
doctype html
html
  head
    title
      | FlightBooker
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
    meta[name="viewport" content="width=device-width, initial-scale=1.0"]
  body
    = render 'layouts/navbar'
    = render 'shared/flash'
    = yield

app/views/passengers/_form.slim
li.collection-item
  h5 Passenger #{p.index + 1}
  .row
    .col.s12.l6
      = p.label :first_name
      = p.text_field :first_name, required: true
    .col.s12.l6
      = p.label :last_name
      = p.text_field :last_name, required: true
    .col.s12.l6
      = p.label :email
      = p.email_field :email, required: true

app/views/passengers/_passenger.slim
li.collection-item.avatar
  i.material-icons.circle.cyan.darken-3 face
  span.title= passenger.full_name
  br
  span.title= passenger.email

app/views/shared/_flash.slim
#flash-container.flash-container
  - flash.each do |message_type, message|
    = content_tag(:div, message,
                        class: "alert flash-#{message_type}",
                        id: 'flash')

app/views/shared/_spinner.slim
#spinner[style='visibility: hidden; position: fixed; top: 0; left: 0; width: 100%; z-index: 9999;']
  .progress[style='margin: 0; background-color: inherit;']
    .indeterminate